# Generated by Django 4.0.6 on 2022-07-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_thing_title_alter_thing_condition_alter_thing_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
