# Generated by Django 4.0.6 on 2022-07-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_thing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='thing',
            name='condition',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
