# Generated by Django 4.0.6 on 2022-07-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_alter_thing_color_alter_thing_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='color',
            field=models.IntegerField(),
        ),
    ]
