# Generated by Django 4.0.6 on 2022-07-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_alter_thing_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
