# Generated by Django 4.0.6 on 2022-07-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_alter_thing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
