# Generated by Django 4.0.6 on 2022-07-20 13:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_alter_thing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=99, scale=None, size=[150, 150], upload_to='images'),
        ),
    ]
