# Generated by Django 4.0.6 on 2022-07-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_user_profiles'),
        ('clothes', '0010_alter_thing_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
